### ISSUE TITLE
Functional clarification

### ISSUE THREAD

**Issue by intrade** [greysoft/mailismus#1]
Hey! I'm looking for mail server implementation and found your project! Looking in to code I have few questions:
- Is there support for Secure SMTP, POP3 + TLS, IMAP + TLS?
- Can it manage multiple virtual domains with virtual users?
- Can it validate PTR, SPF and DMARC records?
- Cant it sign outgoing emails using DMARC keys?

Looking forward,
Thank you in advance.

**Comment by intrade** [comment]
Also I try to build this project but stuck on building NAF. There is failing tests

**Comment by greysoft** [comment]
Hi, in answer to your questions:
1) Yes it supports TLS for all protocols
2) Yes, you can define users, alias and local domains (ie. domains we recognise as the end destination, so that the messages get stored in Mailismus rather than relayed onwards)
3) No it does not validate PTR or DMARC
4) It does not sign outgoing emails

**Comment by greysoft** [comment]
In answer to your build issues, NAF and Mailismus were last built on Java 8-66 and it turns out there are build errors on later Java versions (and even Java 8-301).
I am in the process of fixing the builds for Java 11, but this may take a while in my spare time.

**Comment by greysoft** [comment]
NAF build fixed and pushed to GitHub.
New version published to Maven Central.
